/** @format */

export const locations: { [key: number]: any } = {
  0: {
    id: "algiers",
    lat: 36.7529,
    lng: 3.042,
    name: "Algiers",
    description: "Capital of Algeria",
    opacity: 0.9,
    size: 25,
    url: "https://en.wikipedia.org/wiki/Algiers",
    target: "_blank",
  },
  1: {
    id: "oran",
    lat: 35.6971,
    lng: -0.6308,
    name: "Oran",
    description: "Major port city on the Mediterranean coast",
  },
  2: {
    id: "berrouaghia",
    lat: 36.1378,
    lng: 2.9111,
    name: "Berrouaghia",
    description: "Mountain town in Médéa Province",
    url: "https://en.wikipedia.org/wiki/Berrouaghia",
  },
  3: {
    id: "medea",
    lat: 36.2648,
    lng: 2.7539,
    name: "Médéa",
    description: "Capital of Médéa Province",
  },
  4: {
    id: "constantine",
    lat: 36.365,
    lng: 6.6147,
    name: "Constantine",
    description: "City of bridges and ancient history",
  },
  5: {
    id: "annaba",
    lat: 36.9,
    lng: 7.766,
    name: "Annaba",
    description: "Coastal city in the northeast",
  },
  6: {
    id: "ghardaia",
    lat: 32.4894,
    lng: 3.6731,
    name: "Ghardaïa",
    description: "Historic M'zab Valley city",
  },
  7: {
    id: "bejaia",
    lat: 36.7509,
    lng: 5.0567,
    name: "Bejaia",
    description: "Mediterranean port city",
  },
  8: {
    id: "blida",
    lat: 36.47,
    lng: 2.8333,
    name: "Blida",
    description: "City near the Atlas Mountains",
  },
  9: {
    id: "sidi-bel-abbes",
    lat: 35.2,
    lng: -0.6333,
    name: "Sidi Bel Abbès",
    description: "Known for agriculture and education",
  },
  10: {
    id: "tlemcen",
    lat: 34.8828,
    lng: -1.3164,
    name: "Tlemcen",
    description: "Rich in Moorish architecture and history",
  },
  11: {
    id: "setif",
    lat: 36.1911,
    lng: 5.4137,
    name: "Sétif",
    description: "Major inland city in eastern Algeria",
  },
  12: {
    id: "batna",
    lat: 35.55,
    lng: 6.1667,
    name: "Batna",
    description: "Gateway to the Aurès Mountains",
  },
  13: {
    id: "skikda",
    lat: 36.8663,
    lng: 6.9063,
    name: "Skikda",
    description: "Coastal city with Roman history",
  },
  14: {
    id: "tiaret",
    lat: 35.37,
    lng: 1.32,
    name: "Tiaret",
    description: "Center of historical Berber kingdoms",
  },
};
